"""add newsletter to person

Revision ID: 131fab46ba72
Revises: d25c80bd4598
Create Date: 2020-06-24 11:26:23.215911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131fab46ba72'
down_revision = 'd25c80bd4598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('newsletter', sa.Boolean(), nullable=True))
    op.add_column('person', sa.Column('newsletter_registered', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_person_newsletter'), 'person', ['newsletter'], unique=False)
    op.create_index(op.f('ix_person_newsletter_registered'), 'person', ['newsletter_registered'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_newsletter_registered'), table_name='person')
    op.drop_index(op.f('ix_person_newsletter'), table_name='person')
    op.drop_column('person', 'newsletter_registered')
    op.drop_column('person', 'newsletter')
    # ### end Alembic commands ###
