"""empty message

Revision ID: 7eb908dc688d
Revises: 
Create Date: 2020-05-25 14:57:27.321043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb908dc688d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=32), nullable=True),
    sa.Column('nachname', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('telefon', sa.String(length=32), nullable=True),
    sa.Column('instagram', sa.String(length=32), nullable=True),
    sa.Column('twitter', sa.String(length=32), nullable=True),
    sa.Column('facebook', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestein', sa.Integer(), nullable=True),
    sa.Column('herkunft', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('titel', sa.String(length=128), nullable=True),
    sa.Column('pers_geschichte', sa.String(length=1), nullable=True),
    sa.Column('geo_geschichte', sa.String(length=1), nullable=True),
    sa.Column('bild_stein', sa.String(length=64), nullable=True),
    sa.Column('bild_herkunft', sa.String(length=64), nullable=True),
    sa.Column('absender_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['absender_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['gestein'], ['gestein.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stein_herkunft'), 'stein', ['herkunft'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stein_herkunft'), table_name='stein')
    op.drop_table('stein')
    op.drop_table('person')
    op.drop_table('gestein')
    # ### end Alembic commands ###
