"""first migration

Revision ID: 80f205893080
Revises: 
Create Date: 2020-07-03 12:11:25.795220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f205893080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=32), nullable=True),
    sa.Column('nachname', sa.String(length=32), nullable=True),
    sa.Column('wohnort', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('telefon', sa.String(length=32), nullable=True),
    sa.Column('instagram', sa.String(length=32), nullable=True),
    sa.Column('twitter', sa.String(length=32), nullable=True),
    sa.Column('facebook', sa.String(length=32), nullable=True),
    sa.Column('newsletter', sa.Boolean(), nullable=True),
    sa.Column('newsletter_registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestein', sa.Integer(), nullable=True),
    sa.Column('herkunft', sa.String(length=32), nullable=True),
    sa.Column('land', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('titel', sa.String(length=128), nullable=True),
    sa.Column('pers_geschichte', sa.String(length=1), nullable=True),
    sa.Column('geo_geschichte', sa.String(length=1), nullable=True),
    sa.Column('bild_stein', sa.String(length=64), nullable=True),
    sa.Column('bild_herkunft', sa.String(length=64), nullable=True),
    sa.Column('absender_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=1), nullable=True),
    sa.Column('bemerkungen', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['absender_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['gestein'], ['gestein.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stein_published'), 'stein', ['published'], unique=False)
    op.create_table('bild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('stein', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stein'], ['stein.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bild')
    op.drop_index(op.f('ix_stein_published'), table_name='stein')
    op.drop_table('stein')
    op.drop_table('person')
    op.drop_table('gestein')
    # ### end Alembic commands ###
