"""add language and emailsent

Revision ID: 95ed91372a2b
Revises: 80f205893080
Create Date: 2020-07-04 15:07:19.320862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ed91372a2b'
down_revision = '80f205893080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stein', sa.Column('emailSent', sa.Boolean(), nullable=True))
    op.add_column('stein', sa.Column('language', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stein', 'language')
    op.drop_column('stein', 'emailSent')
    # ### end Alembic commands ###
