"""add description

Revision ID: 9a244e91d36d
Revises: ad54135d67a6
Create Date: 2020-06-21 12:06:48.856990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a244e91d36d'
down_revision = 'ad54135d67a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stein', sa.Column('description', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stein', 'description')
    # ### end Alembic commands ###
