"""add country

Revision ID: ad54135d67a6
Revises: b40c0134c30a
Create Date: 2020-06-15 11:56:38.677291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad54135d67a6'
down_revision = 'b40c0134c30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stein', sa.Column('land', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_stein_published'), 'stein', ['published'], unique=False)
    op.drop_index('ix_stein_herkunft', table_name='stein')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stein_herkunft', 'stein', ['herkunft'], unique=False)
    op.drop_index(op.f('ix_stein_published'), table_name='stein')
    op.drop_column('stein', 'land')
    # ### end Alembic commands ###
