"""Person wohnort

Revision ID: b40c0134c30a
Revises: 7eb908dc688d
Create Date: 2020-06-07 10:43:28.777166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40c0134c30a'
down_revision = '7eb908dc688d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('wohnort', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'wohnort')
    # ### end Alembic commands ###
